import { useEffect, useMemo, useState } from 'react'
import './App.css'

const NAV = [
  ['Today', '⌂'], ['Family Space', '◌'], ['My Vault', '◇'], ['People', '♧'], ['Timeline', '↗'], ['Library', '▦'], ['Agent Studio', '✦'],
]
const items = [
  {title:'School open morning', type:'Document', space:'Family Space', date:'Today', icon:'▤'},
  {title:'Aileen’s beach voice note', type:'Voice memory', space:'Aileen', date:'8 Jun 2022', icon:'◖'},
  {title:'Summer holiday ideas', type:'Note', space:'Private to me', date:'Yesterday', icon:'✦'},
  {title:'Birthday cake inspiration', type:'Photo', space:'Family Space', date:'4 Jun', icon:'◒'},
  {title:'Home insurance renewal', type:'Document', space:'Private to me', date:'28 May', icon:'▤'},
]
const people = [
  {name:'Umer Hadeed', initials:'UH', role:'You', tone:'blue', access:'Private vault'},
  {name:'Sara', initials:'SA', role:'Partner', tone:'orange', access:'Own private vault'},
  {name:'Aileen', initials:'AI', role:'Child profile', tone:'pink', access:'Parent managed'},
  {name:'Hasn', initials:'HA', role:'Child profile', tone:'gold', access:'Parent managed'},
]
const seedMessages = [
  {from:'Sara', initials:'SA', tone:'orange', time:'9:12 AM', body:'School has confirmed the open morning for next Friday.'},
  {from:'You', initials:'UH', tone:'blue', time:'9:15 AM', body:'Great. I have added it to the family calendar.'},
  {from:'Family AI', initials:'AI', tone:'green', time:'9:16 AM', ai:true, body:'I found the school email and created a shared event for Friday, 14 June at 9:30 AM.', sources:['School email','Family calendar']},
]
const agents = [
  {name:'Family AI', initials:'AI', tone:'green', purpose:'Shared context, family chat and practical coordination', spaces:'Family Space only', model:'OpenAI GPT-4.1', status:'Ready'},
  {name:'Aileen’s Story', initials:'AS', tone:'pink', purpose:'Source-linked milestones, memories and future messages', spaces:'Aileen profile + selected shared memories', model:'OpenRouter · Claude', status:'Draft'},
]
function Avatar({initials,tone='blue',small=false}) { return <span className={`avatar ${tone} ${small?'small':''}`}>{initials}</span> }
function Toast({children}) { return <div className="toast">✓ {children}</div> }
function Modal({title,children,onClose}) { useEffect(()=>{const key=e=>e.key==='Escape'&&onClose();window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[onClose]); return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal" role="dialog" aria-modal="true" aria-label={title}><header><div><p className="eyebrow">PRIVATE FAMILY OS</p><h2>{title}</h2></div><button className="close" onClick={onClose} aria-label="Close">×</button></header>{children}</section></div> }

export default function App(){
  const [page,setPage]=useState('Today'); const [query,setQuery]=useState(''); const [toast,setToast]=useState(''); const [modal,setModal]=useState(null); const [messages,setMessages]=useState(seedMessages); const [agentList,setAgentList]=useState(agents)
  const flash=text=>{setToast(text);setTimeout(()=>setToast(''),3200)}
  const filtered=useMemo(()=>items.filter(x=>Object.values(x).join(' ').toLowerCase().includes(query.toLowerCase())),[query])
  const addMessage=text=>{if(!text.trim())return;setMessages(m=>[...m,{from:'You', initials:'UH',tone:'blue',time:'Now',body:text.trim()}])}
  return <div className="shell"><aside className="sidebar"><div className="brand"><span className="logo">p</span><span>private</span></div><button className="capture" onClick={()=>setModal('capture')}>+ Add to your life</button><nav>{NAV.map(([name,icon])=><button key={name} onClick={()=>setPage(name)} className={page===name?'active':''}><span>{icon}</span>{name}</button>)}</nav><div className="sidebar-foot"><div className="secure">⌁ <span><b>Private by design</b><small>You choose what gets shared.</small></span></div><button className="account"><Avatar initials="UH" tone="blue" small/><span><b>Umer Hadeed</b><small>Family owner</small></span><i>⌄</i></button></div></aside><main><header className="topbar"><div className="mobile-logo"><span className="logo">p</span> private</div><label className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your private life"/></label><div className="top-actions"><button onClick={()=>flash('No new notifications.')}>⌁</button><button onClick={()=>setModal('privacy')}>⌘</button></div></header><div className="content">{toast&&<Toast>{toast}</Toast>}{page==='Today'&&<Today open={setModal} setPage={setPage}/>} {page==='Family Space'&&<FamilySpace messages={messages} addMessage={addMessage} flash={flash}/>} {page==='My Vault'&&<Vault data={filtered} open={setModal} flash={flash}/>} {page==='People'&&<People open={setModal} flash={flash}/>} {page==='Timeline'&&<Timeline flash={flash}/>} {page==='Library'&&<Library data={filtered} open={setModal} flash={flash}/>} {page==='Agent Studio'&&<AgentStudio agents={agentList} open={setModal} flash={flash}/>}</div></main>{modal==='capture'&&<Capture close={()=>setModal(null)} flash={flash}/>} {modal==='privacy'&&<Privacy close={()=>setModal(null)}/>} {modal==='create-agent'&&<CreateAgent close={()=>setModal(null)} add={agent=>{setAgentList(a=>[...a,agent]);flash('Agent created as a draft. Connect a provider when you are ready.')}}/>} {modal==='connect-model'&&<ConnectModel close={()=>setModal(null)} flash={flash}/>}</div>
}
function Title({eyebrow,title,text,action,onAction}){return <div className="title"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p></div>{action&&<button className="primary" onClick={onAction}>+ {action}</button>}</div>}
function Today({open,setPage}){return <><Title eyebrow="SATURDAY, 8 JUNE" title="Good morning, Umer." text="Everything important, in one calm place." action="Set up your household" onAction={()=>open('privacy')}/><section className="dash-grid"><article className="card day"><div className="card-heading"><div><p className="eyebrow">YOUR DAY</p><h2>At a glance</h2></div><button>Calendar →</button></div>{[['10:30','Football practice','Hasn · Eastfield Sports Club'],['16:00','Order birthday cake','Reminder · Aileen’s birthday is in 12 days'],['19:30','Family time','Saved as a gentle reminder']].map(x=><div className="agenda" key={x[0]}><time>{x[0]}</time><div><b>{x[1]}</b><small>{x[2]}</small></div></div>)}</article><article className="card memory"><p className="eyebrow">ON THIS DAY · 2022</p><h2>Aileen’s first beach day</h2><p>Four years ago, you saved a voice note from this day.</p><button onClick={()=>setPage('Timeline')}>Open memory →</button></article></section><section className="section-title"><div><p className="eyebrow">YOUR FAMILY</p><h2>People who matter</h2></div><button onClick={()=>setPage('People')}>Manage people →</button></section><div className="people-strip">{people.slice(0,3).map(p=><div className="person" key={p.name}><Avatar initials={p.initials} tone={p.tone}/><span><b>{p.name}</b><small>{p.role}</small></span></div>)}<button className="add-person" onClick={()=>setPage('People')}>+<small>Add someone</small></button></div><section className="card short-chat"><div><p className="eyebrow">FAMILY SPACE</p><h2>Keep the family in the loop</h2><p>Discuss, capture and organise family life in one private shared conversation.</p></div><button className="secondary" onClick={()=>setPage('Family Space')}>Open Family Space →</button></section></>}
function FamilySpace({messages,addMessage,flash}){const [text,setText]=useState('');return <><Title eyebrow="SHARED WITH YOUR HOUSEHOLD" title="Family Space" text="A private conversation for invited people and permissioned AI." action="Invite member" onAction={()=>flash('Invitations will show the exact access granted.')}/><div className="chat-layout"><section className="card chat"><div className="chat-head"><div><div className="member-stack">{people.map(p=><Avatar key={p.name} initials={p.initials} tone={p.tone} small/>)}<Avatar initials="AI" tone="green" small/></div><h2>Umer’s household</h2><small>4 members · Family AI: Family Space only</small></div><button className="pill">⌁ Access rules</button></div><div className="messages">{messages.map((m,i)=><div className="message" key={i}><Avatar initials={m.initials} tone={m.tone}/><div><p><b>{m.from}</b> <small>{m.time}</small>{m.ai&&<em>Family AI</em>}</p><span>{m.body}</span>{m.sources&&<div className="sources">{m.sources.map(s=><button key={s}>↗ {s}</button>)}</div>}</div></div>)}</div><form className="composer" onSubmit={e=>{e.preventDefault();addMessage(text);setText('')}}><button type="button">+</button><input value={text} onChange={e=>setText(e.target.value)} placeholder="Write to your Family Space"/><button className="send">↑</button></form></section><aside className="card action-card"><p className="eyebrow">DO MORE WITH THIS CHAT</p><button onClick={()=>flash('Saved as a shared memory for Aileen.')}>✦ <span>Save a memory</span></button><button onClick={()=>flash('Created a shared task.')}>✓ <span>Create a task</span></button><button onClick={()=>flash('A source-linked summary is ready.')}>≡ <span>Summarise chat</span></button><div className="access-note"><b>⌁ Family AI access</b><p>Family Space only. Private adult vaults are excluded.</p></div></aside></div></>}
function Vault({data,open,flash}){return <><Title eyebrow="PRIVATE TO YOU" title="My Vault" text="Your personal notes, memories and documents. Nothing is shared without your approval." action="Add item" onAction={()=>open('capture')}/><Toolbar/><div className="table card"><div className="table-head"><span>Name</span><span>Type</span><span>Space</span><span>Added</span><span/></div>{data.map(i=><div className="row" key={i.title}><span className="file"><i>{i.icon}</i><b>{i.title}</b></span><span>{i.type}</span><span className={i.space==='Private to me'?'tag private':'tag'}>{i.space}</span><span>{i.date}</span><button onClick={()=>flash(`${i.title} opened with its source and access settings.`)}>Open →</button></div>)}</div></>}
function Toolbar(){return <div className="toolbar"><div><button className="selected">All items</button><button>Memories</button><button>Documents</button><button>Voice notes</button></div><small>Encrypted and private</small></div>}
function People({open,flash}){return <><Title eyebrow="YOUR HOUSEHOLD" title="People and access" text="Every person has their own profile. Private information remains private until it is deliberately shared." action="Add someone" onAction={()=>open('capture')}/><div className="profile-grid">{people.map(p=><article className="card profile" key={p.name}><Avatar initials={p.initials} tone={p.tone}/><div className="profile-title"><div><h2>{p.name}</h2><p>{p.role}</p></div><button onClick={()=>flash(`Opening access settings for ${p.name}.`)}>Manage →</button></div><p><span>Vault access</span><b>{p.access}</b></p><p><span>Family Space</span><b>{p.role==='You'||p.role==='Partner'?'Member':'Visible to parents'}</b></p><p><span>AI rules</span><b>Permissioned only</b></p></article>)}</div></>}
function Timeline({flash}){const list=[['8 Jun 2022','Aileen’s first beach day','Voice memory and 14 photos'],['14 Mar 2024','First day at nursery','Family-shared note and photo'],['7 Jun 2026','School open morning confirmed','Family Space conversation']];return <><Title eyebrow="YOUR FAMILY STORY" title="Timeline" text="A calm, source-linked record of the moments you choose to keep." action="Add a memory" onAction={()=>flash('Choose a memory type and a person to add it to.')}/><section className="card timeline">{list.map(x=><div className="event" key={x[0]}><time>{x[0]}</time><i/><div><h2>{x[1]}</h2><p>{x[2]}</p><button onClick={()=>flash('Source details opened.')}>View sources →</button></div></div>)}</section></>}
function Library({data,open,flash}){return <><Title eyebrow="YOUR FAMILY LIBRARY" title="Files and memories" text="Browse approved material across the spaces you can access." action="Upload files" onAction={()=>open('capture')}/><div className="library">{data.map(i=><article className="card" key={i.title}><div className="library-icon">{i.icon}</div><p className="eyebrow">{i.type} · {i.space}</p><h2>{i.title}</h2><p>Added {i.date}</p><button onClick={()=>flash(`${i.title} is ready to view.`)}>Open item →</button></article>)}</div></>}
function AgentStudio({agents,open,flash}){return <><Title eyebrow="YOUR AI TEAM" title="Agent Studio" text="Create purpose-led agents. Set their access, model route and approval rules before they ever see family context." action="Create agent" onAction={()=>open('create-agent')}/><div className="agent-banner"><div><span>⌁</span><div><b>Start with boundaries, not prompts.</b><p>An agent can access only the spaces you select. It never receives an entire family vault.</p></div></div><button className="secondary" onClick={()=>open('connect-model')}>Manage model providers →</button></div><div className="agent-grid">{agents.map(a=><article className="card agent" key={a.name}><div className="agent-top"><Avatar initials={a.initials} tone={a.tone}/><span className={a.status==='Ready'?'status ready':'status'}>{a.status}</span></div><h2>{a.name}</h2><p>{a.purpose}</p><div className="agent-meta"><span>Access</span><b>{a.spaces}</b><span>Model route</span><b>{a.model}</b></div><div className="agent-actions"><button onClick={()=>flash(`${a.name} opened in editor.`)}>Edit agent</button><button onClick={()=>open('connect-model')}>Model settings</button></div></article>)}</div><section className="card provider-card"><div><p className="eyebrow">MODEL ROUTING</p><h2>Use one provider now. Stay flexible later.</h2><p>OpenAI API gives a direct GPT route. OpenRouter lets you route to multiple models with one API. Codex subscription access is not a production API route, so the app should use the OpenAI API for OpenAI models.</p></div><button className="primary" onClick={()=>open('connect-model')}>Connect a provider</button></section></>}
function Capture({close,flash}){return <Modal title="Add to your life" onClose={close}><p className="modal-copy">Choose what you want to add. You will select the right person and visibility before it is saved.</p><div className="capture-grid">{[['✦','Written memory'],['◖','Voice note'],['◒','Photo or video'],['▤','Document']].map(x=><button key={x[1]} onClick={()=>{close();flash(`${x[1]} capture is ready in the production build.`)}}><i>{x[0]}</i><b>{x[1]}</b><small>Choose privacy next</small></button>)}</div></Modal>}
function Privacy({close}){return <Modal title="Your privacy" onClose={close}><div className="privacy-list"><div><b>⌁ Your private vault</b><p>Only you can view it. It is not part of Family Space or available to Family AI by default.</p></div><div><b>◌ Family Space</b><p>Shared only with members you invite. Family AI can access content here when it has permission.</p></div><div><b>✦ Agent access</b><p>Every agent has its own defined scope. You can review, edit or revoke it at any time.</p></div></div><button className="primary full" onClick={close}>I understand</button></Modal>}
function CreateAgent({close,add}){const [name,setName]=useState('');const [provider,setProvider]=useState('OpenAI API');const [space,setSpace]=useState('Family Space only');return <Modal title="Create an agent" onClose={close}><div className="form-grid"><label>Agent name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Home AI"/></label><label>Purpose<select defaultValue="Household coordination"><option>Household coordination</option><option>Family memories and legacy</option><option>Child timeline</option><option>Personal private assistant</option></select></label><label>Access scope<select value={space} onChange={e=>setSpace(e.target.value)}><option>Family Space only</option><option>Selected shared memories</option><option>Specific child profile</option><option>My private vault</option></select></label><label>Model route<select value={provider} onChange={e=>setProvider(e.target.value)}><option>OpenAI API</option><option>OpenRouter API</option></select></label></div><div className="warning"><b>Permission check</b><p>The agent will access only {space.toLowerCase()}. You can change or revoke this later.</p></div><div className="modal-actions"><button className="secondary" onClick={close}>Cancel</button><button className="primary" onClick={()=>{add({name:name||'New Family Agent',initials:(name||'NA').slice(0,2).toUpperCase(),tone:'gold',purpose:'Purpose and model route can be refined before activation.',spaces:space,model:provider,status:'Draft'});close()}}>Create draft →</button></div></Modal>}
function ConnectModel({close,flash}){const [selected,setSelected]=useState('OpenAI API');const [key,setKey]=useState('');return <Modal title="Connect a model provider" onClose={close}><p className="modal-copy">Provider keys must live on the backend, never in the desktop or mobile app. This prototype stores nothing.</p><div className="provider-options"><button className={selected==='OpenAI API'?'selected-provider':''} onClick={()=>setSelected('OpenAI API')}><b>OpenAI API</b><span>Direct access to GPT models. Use this route for OpenAI models and Codex-related capabilities exposed through the API.</span></button><button className={selected==='OpenRouter API'?'selected-provider':''} onClick={()=>setSelected('OpenRouter API')}><b>OpenRouter API</b><span>One API for multiple providers and models, with per-agent routing flexibility.</span></button></div><label className="key-label">{selected} key<input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="Paste only when the secure backend is connected"/></label><div className="warning"><b>Security requirement</b><p>Do not ship an API key in the frontend. The production build will save this encrypted in server-side secrets and use a backend proxy with user permissions and audit logs.</p></div><div className="modal-actions"><button className="secondary" onClick={close}>Cancel</button><button className="primary" onClick={()=>{close();flash(`${selected} configuration saved as a prototype setting. No key was stored.`)}}>Save provider →</button></div></Modal>}
